# 1
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [11]:
np.cov(zp,ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [8]:
cov = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov

9157.839999999997

In [12]:
np.cov(zp,ks, ddof = 1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [13]:
np.std(zp, ddof = 1)

62.31318747531162

In [14]:
np.std(ks, ddof = 1)

183.99544076477068

In [15]:
corrcoef = 10175.38 / (np.std(zp, ddof = 1) * np.std(ks, ddof = 1))
corrcoef

0.8874902858947499

In [17]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [19]:
import pandas as pd

In [22]:
df = pd.DataFrame({'zp': zp, 'ks': ks}, columns = ['zp', 'ks'])
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [27]:
df.cov().values[0,1] / (zp.std(ddof = 1) * ks.std(ddof = 1))

0.887490092073916

In [28]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

# 2
Измерены значения IQ выборки студентов,обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.

Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [32]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq.shape

(10,)

In [30]:
mean_iq = iq.mean()
mean_iq

118.1

In [31]:
std_iq = np.std(iq, ddof = 1)
std_iq

10.54566788359614

In [34]:
2.262 * std_iq / np.sqrt(10)

7.543392236918348

In [37]:
confid_iq_low = mean_iq - 7.54
confid_iq_low

110.55999999999999

In [38]:
confid_iq_hig = mean_iq + 7.54
confid_iq_hig

125.64

# 3
Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. 

Найдите доверительный интервал для математического ожидания с надежностью 0.95.