<a href="https://colab.research.google.com/github/Elena8719/math/blob/main/%D0%BA%D0%BE%D1%80%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
s=np.array([27, 37, 42, 48, 56, 57, 77, 80])
s

array([27, 37, 42, 48, 56, 57, 77, 80])

In [ ]:
p = np.array([1.2, 1.6, 1.8, 1.8, 2.6, 2.5, 3, 3.3])
p

array([1.2, 1.6, 1.8, 1.8, 2.6, 2.5, 3. , 3.3])

In [ ]:
np.corrcoef(p, s)

array([[1.        , 0.97857682],
       [0.97857682, 1.        ]])

In [ ]:
import scipy.stats as stats


In [ ]:
stats.spearmanr(p, s)


SpearmanrResult(correlation=0.9700772721497398, pvalue=6.548558831120599e-05)

In [ ]:
np.sort(s)

array([27, 37, 42, 48, 56, 57, 77, 80])

In [ ]:
s_r=np.array([1, 2, 3, 4, 5, 6, 7, 8])
s

array([27, 37, 42, 48, 57, 56, 77, 80])

In [ ]:
p_r = np.array  ([1, 2, 3.5, 3.5, 5, 6, 7, 8 ])
p_r

array([1. , 2. , 3.5, 3.5, 5. , 6. , 7. , 8. ])

In [ ]:
np.corrcoef(s_r, p_r)

array([[1.       , 0.9940298],
       [0.9940298, 1.       ]])

In [ ]:
m=np.array([31, 32, 33, 34, 35, 35, 40, 41, 42, 46])
m
len(m)

10

In [ ]:
v = np.array([7.7, 8.3, 7.6, 9.1, 9.6, 9.9, 11.8, 12.2, 14.8, 15.8])
v
len(v)

10

In [ ]:
np.sort(m)

array([31, 32, 33, 35, 35, 40, 41, 42, 46])

In [ ]:
stats.spearmanr(v, m)

SpearmanrResult(correlation=0.960490759014502, pvalue=1.0163235882999591e-05)

In [ ]:
v_1 = np.array([2, 3, 1, 4, 5, 6, 7, 8, 9, 10])
v_1

array([ 2,  3,  1,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m_1 = np.array([1, 2, 3, 4, 5.5, 5.5, 7, 8, 9, 10])

In [ ]:
np.corrcoef(v_1, m_1)

array([[1.        , 0.96049076],
       [0.96049076, 1.        ]])

In [ ]:
s2 = np.array([1, 2, 3, 4, 6, 5, 7, 8])

In [ ]:
p2= np.array([1, 2, 3.5, 3.5, 5, 6, 7, 8])

In [ ]:
np.corrcoef(s2, p2)

array([[1.        , 0.97007727],
       [0.97007727, 1.        ]])