In [1]:
import numpy as np

In [2]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

In [3]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

# Задание_1

### with intercept

In [4]:
b = (np.mean(x * y) - np.mean(x) * np.mean(y)) / (np.mean(x**2) - np.mean(x) ** 2)
b

2.620538882402765

In [5]:
a = np.mean(y) - b * np.mean(x)
a

444.1773573243596

получим:
y = 444.18 + (2.62)x

### without intercept 

In [6]:
x = x.reshape((10,1))
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [7]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [8]:
B = np.linalg.inv(x.T @ x) @ x.T @ y
B

array([[5.88982042]])

получаем: y = 5.89x

# Задание_2

In [9]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

In [10]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [11]:
n = 10

In [12]:
alpha = 0.000001

In [13]:
B1 = 0

In [14]:
for i in range(10000):
    B1 -= alpha * (2/n) * np.sum((B1*x - y) * x)
    if i % 1000 == 0:
        print(B1)

0.1622834
5.889820420128484
5.889820420132673
5.889820420132673
5.889820420132673
5.889820420132673
5.889820420132673
5.889820420132673
5.889820420132673
5.889820420132673


# Задание_3

In [15]:
a = 0
b = 0
alpha = 0.000001
n = len(x)

for _ in range(10000):
    pred = a + b * x
    resid = y - pred
    a -= alpha * ((2/n) * np.sum(resid) * -1)
    b -= alpha * ((2/n) * resid.dot(x) * -1)
print(f'a = {a}, b = {b}')

a = 2.290747176883373, b = 5.873019702381174
