In [ ]:
#1

In [10]:
import numpy as np
zp=np.array([35,45,190,200,40,70,54,150,120,110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [11]:
ks=np.array([401,574,874,919,459,739,653,902,746,832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [24]:
cov=np.mean(zp*ks)-np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [38]:
np.cov(zp,ks,ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [34]:
s1=np.std(zp)
s1

59.115480206118605

In [35]:
s2=np.std(ks)
s2

174.55340157098058

In [36]:
corr=cov/(s1*s2)
corr

0.8874900920739158

In [25]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [ ]:
#2

In [39]:
iq=np.array([131,125,115,122,131,115,107,99,125,111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [58]:
np.mean(iq)

118.1

In [60]:
np.shape(iq)

(10,)

In [44]:
s=np.std(iq,ddof=1)
s

10.54566788359614

In [57]:
from scipy import stats
t=stats.t.ppf(1-0.05/2,9)
t

2.2621571627409915

In [61]:
118.1+2.262*s/np.sqrt(10)

125.64339223691834

In [62]:
118.1-2.262*s/np.sqrt(10)

110.55660776308164

In [63]:
# доверительный интервал [110.5566;125.6434]

In [64]:
#3

In [30]:
# a/2=0.25, z=1.96

In [31]:
import numpy as np
174.2+1.96*5/np.sqrt(27)

176.08601087935276

In [32]:
174.2-1.96*5/np.sqrt(27)

172.31398912064722

In [ ]:
# доверителный интервал [172.3139;176.086]