# 1 
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): 

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], 

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. 

Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). 

Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np

In [4]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [5]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
X.shape

(10,)

In [7]:
b = (np.mean(X * y) - np.mean(X) * np.mean(y)) / (np.mean(X**2) - np.mean(X) ** 2)
b

2.620538882402765

In [8]:
a = np.mean(y) - b * np.mean(X)
a

444.1773573243596

y = 444.18 + 2.62x

In [9]:
r = b * np.std(X) / np.std(y)
r

0.8874900920739162

In [10]:
R2 = r**2
R2

0.7876386635293682

In [11]:
import seaborn as sns

In [13]:
X = X.reshape((10,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [14]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [17]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)),X.T@y)
B

array([[5.88982042]])

# 2 
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept). 

# 3. 
Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [18]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [19]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [20]:
def mse_ (B1, y=y, X=X, n= 10):
    return np.sum((B1 * X - y)**2)/n

In [21]:
B1 = 0.1

In [25]:
alpha = 1e-6
alpha

1e-06

In [28]:
n=10

In [33]:
for i in range (500):
    B1 -= alpha * (2/n) * np.sum ((B1*X-y)*X)
    if i%100 == 0:
        print ('Iteration : {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse= mse_(B1)))

Iteration : 0, B1=5.889820420132673, mse=56516.85841571943
Iteration : 100, B1=5.889820420132673, mse=56516.85841571943
Iteration : 200, B1=5.889820420132673, mse=56516.85841571943
Iteration : 300, B1=5.889820420132673, mse=56516.85841571943
Iteration : 400, B1=5.889820420132673, mse=56516.85841571943


# 3

In [82]:
B1 = 0.1
B0 = 0.1

In [83]:
def mse2_ (B0, B1, y=y, X=X, n= 10):
    return np.sum((B0 + B1 * X - y)**2)/n

In [90]:
alpha = 7e-5
alpha

7e-05

In [92]:
for i in range (1000000):
    y_p = B0 + B1 * X
    B0 -= alpha * (2/n) * np.sum((y_p-y))
    B1 -= alpha * (2/n) * np.sum((y_p-y)*X)
    if i%200000 == 0:
        print ('Iteration:{i}, B0={B0}, B1={B1}, mse={mse}'.format(i=i,B0=B0,B1=B1,mse=mse2_(B0,B1)))

Iteration:0, B0=443.62888568851605, B1=2.6245758761358142, mse=6470.490508942971
Iteration:200000, B0=444.1769058439322, B1=2.6205422054983227, mse=6470.414201228363
Iteration:400000, B0=444.177356952718, B1=2.620538885138212, mse=6470.414201176658
Iteration:600000, B0=444.17735732355993, B1=2.6205388824086526, mse=6470.414201176661
Iteration:800000, B0=444.17735732355993, B1=2.6205388824086526, mse=6470.414201176661
