<a href="https://colab.research.google.com/github/Elena8719/math/blob/main/%D0%A1%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%80%207.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy.stats as stats

In [11]:
gr1=np.array([0.5, 0.7, 1, 1.2, 1.4])
gr2= np.array([1.3, 1.45, 1.6, 1.7, 1.8])
gr3=np.array([6.2, 12.6, 13.2, 14.1, 14.2])

In [12]:
stats.kruskal( gr1, gr2, gr3)

KruskalResult(statistic=12.02000000000001, pvalue=0.002454088180413905)

In [6]:
x = np.array([0.5, 0.7, 1, 1.2, 1.4, 1.4, 1.2, 1.4, 1.6, 1.7, 1.8,6.2, 12.6, 13.2, 14.1 ])
x

array([ 0.5,  0.7,  1. ,  1.2,  1.4,  1.4,  1.2,  1.4,  1.6,  1.7,  1.8,
        6.2, 12.6, 13.2, 14.1])

In [7]:
x.sort()
x

array([ 0.5,  0.7,  1. ,  1.2,  1.2,  1.4,  1.4,  1.4,  1.6,  1.7,  1.8,
        6.2, 12.6, 13.2, 14.1])

In [13]:
A= np.array([3.5, 3.3, 4.9, 3.6])
A

array([3.5, 3.3, 4.9, 3.6])

In [14]:
B= np.array([8.6, 5.4, 8.8, 5.6])
B

array([8.6, 5.4, 8.8, 5.6])

In [15]:
C=np.array([5.1, 8.6, 7.7, 5.0])

In [16]:
stats.friedmanchisquare(A, B, C)

FriedmanchisquareResult(statistic=6.5, pvalue=0.03877420783172202)