<a href="https://colab.research.google.com/github/Elena8719/math/blob/main/%D0%A2%D0%B5%D1%80%D0%B2%D0%B5%D1%803%20%D0%B2%D0%B5%D1%81%D1%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
z= np.array([100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150])
z

array([100,  80,  75,  77,  89,  33,  45,  25,  65,  17,  30,  24,  57,
        55,  70,  75,  65,  84,  90, 150])

In [8]:
z.shape

(20,)

In [10]:
z.sort()
z

array([ 17,  24,  25,  30,  33,  45,  55,  57,  65,  65,  70,  75,  75,
        77,  80,  84,  89,  90, 100, 150])

In [11]:
(z[9]+z[10])/2

67.5

In [13]:
z= np.array([1, 2, 4, 2, 1, 5, 7, 2, 3, 5, 7, 8, 9])
z

array([1, 2, 4, 2, 1, 5, 7, 2, 3, 5, 7, 8, 9])

In [16]:
z.sort()
z

array([1, 1, 2, 2, 2, 3, 4, 5, 5, 7, 7, 8, 9])

Если n * k/100  целое число, то k-я  перцентиль- это среднее значение элементов под номерами n*k/100 и n*k/100+1

Если  n * k/100 не целое число, то k-я персентиль совпадает с измерением j+1, где j - максимальное целое число, которое меньше, чем  n * k/100

In [14]:
n= len(z)
n

13

In [18]:
k=25

In [19]:
n*k/100

3.25

In [20]:
3+1

4

In [21]:
z[3]

2