<a href="https://colab.research.google.com/github/Elena8719/math/blob/main/%D0%A3%D0%B8%D0%BB%D0%BA%D0%BE%D0%BA%D1%81%D0%BE%D0%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import scipy.stats as stats

In [ ]:
x1= np.array([47, 90, 75])
x1

array([47, 90, 75])

In [ ]:
x2 = np.array([ 58, 60, 77])

In [ ]:
stats.mannwhitneyu(x1, x2)

MannwhitneyuResult(statistic=5.0, pvalue=1.0)

Рассмотрим пример из книги Стентона Гланца


In [ ]:
group_1= np.array ([1000, 1380, 1200])
group_2 = np.array ([1400, 1600, 1180, 1220])

In [ ]:
stats.mannwhitneyu(group_1, group_2)

MannwhitneyuResult(statistic=3.0, pvalue=0.4)

In [ ]:
x1= np.array ([70,74, 74.5, 79, 85, 93, 94, 98, 106.5, 107])

In [ ]:
x2= np.array ([64, 76.5, 67, 73.5, 89, 85, 89.5, 91, 98, 100.5])

In [ ]:
x3= np.array ([64, 76.5, 67, 73.5, 89, 85, 89.5, 91, 98, 113.5])

In [ ]:
stats.wilcoxon(x1, x3)

WilcoxonResult(statistic=9.0, pvalue=0.064453125)

In [ ]:
x2 - x1

array([-6. ,  2.5, -7.5, -5.5,  4. , -8. , -4.5, -7. , -8.5, -6.5])

In [ ]:
stats.wilcoxon(x1, x2)

WilcoxonResult(statistic=3.0, pvalue=0.009765625)

In [ ]:
g1 = np.array([20, 23, 21, 25, 18, 17, 18, 24, 20, 23, 26, 19])
g2 = np.array([21, 25, 20, 22, 23, 18, 17, 28, 24, 27, 21, 23])

In [ ]:
stats.wilcoxon(g1, g2)

/usr/local/lib/python3.7/dist-packages/scipy/stats/morestats.py:3141: UserWarning: Exact p-value calculation does not work if there are ties. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


WilcoxonResult(statistic=17.5, pvalue=0.16500116168404932)

In [ ]:
g1-g2

array([-1, -2,  1,  3, -5, -1,  1, -4, -4, -4,  5, -4])