<a href="https://colab.research.google.com/github/Elena8719/math/blob/main/%D0%A3%D1%80%D0%BE%D0%BA%209%20%D0%BB%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F%20%D1%86%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%BC%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [123]:
import numpy as np
s=np.array([27, 37, 42, 48, 57, 56, 77, 80])

p = np.array([1.2, 1.6, 1.8, 1.8, 2.5, 2.6, 3, 3.3])


In [6]:
n=8

In [7]:
b1 = (n*np.sum(p*s)- np. sum(s) * np.sum(p))/(n* np.sum(s**2)- np.sum(s)**2)

0.03874584717607981

или 2й способ:

In [4]:
b1= (np.mean(s*p)-np.mean(s)*np.mean(p))/(np.mean(s**2)-np.mean(s)**2)
b1

0.03874584717607981

In [43]:
b0 = np.mean(p)-b1*np.mean(s)
b0

0.17147009966776983

In [124]:
y_pred=0.17147009 +0.03874585 * s 
y_pred

array([1.21760804, 1.60506654, 1.79879579, 2.03127089, 2.37998354,
       2.34123769, 3.15490054, 3.27113809])

In [10]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [125]:
model = LinearRegression()

<function ndarray.reshape>

In [126]:
s=s.reshape(-1,1)


In [127]:
regres=model.fit(s,p)


In [128]:
print(model.intercept_)

0.1714700996677747


In [129]:
print(model.coef_)

[0.03874585]


In [145]:
y_pred = model.predict(s)
y_pred



array([1.21760797, 1.60506645, 1.79879568, 2.03127076, 2.37998339,
       2.34123754, 3.15490033, 3.27113787])

In [57]:
df = pd.DataFrame({'реальные': p, 'предсказанные': y_pred})
df

реальные  предсказанные
0       1.2       1.217608
1       1.6       1.605066
2       1.8       1.798796
3       1.8       2.031271
4       2.5       2.379983
5       2.6       2.341238
6       3.0       3.154900
7       3.3       3.271138

In [ ]:
# матричный метод

In [81]:
s=np.array([27, 37, 42, 48, 57, 56, 77, 80])
p = np.array([1.2, 1.6, 1.8, 1.8, 2.5, 2.6, 3, 3.3])
x =s.reshape((8,1))
x


array([[27],
       [37],
       [42],
       [48],
       [57],
       [56],
       [77],
       [80]])

In [82]:
y= p.reshape((8,1))
y

array([[1.2],
       [1.6],
       [1.8],
       [1.8],
       [2.5],
       [2.6],
       [3. ],
       [3.3]])

In [86]:
X = np.hstack([np.ones((8,1)),x])

In [88]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)), X.T @ y)
B

array([[0.1714701 ],
       [0.03874585]])

In [89]:
# Градиентный спуск

In [ ]:
x=np.array([27, 37, 42, 48, 57, 56, 77, 80])
y = np.array([1.2, 1.6, 1.8, 1.8, 2.5, 2.6, 3, 3.3])

In [90]:
def mse_(B1, y = y, x = x, n = 8):
  return np.sum((B1*x - y)**2)/ n
  

In [91]:
alpha  = 1e-6

In [93]:
#mse=  1/n *  np.su,((B1*x - y)**2)

In [94]:
#mse = (2/n) * np.sum((B1*X -y) * X)

In [95]:
B1 = 0.1

In [96]:
n = 8

In [100]:
for i in range (10):
    B1 -= alpha * (2/n)  * np.sum ((B1 * x - y) * x)
    print ('B1 = {}'.format(B1))

B1 = 0.09963717500000001
B1 = 0.0992766067715
B1 = 0.09891828127738128
B1 = 0.09856218456783597
B1 = 0.09820830277982404
B1 = 0.09785662213653352
B1 = 0.09750712894684428
B1 = 0.09715980960479491
B1 = 0.09681465058905309
B1 = 0.09647163846238918


In [106]:
for i in range (100):
    B1 -= alpha * (2/n)  * np.sum ((B1 * x - y) * x)
    if i % 10 == 0:
        print ('Iteranion = {i}, B1 = {B1}, mse ={mse}'.format(i= i, B1 = B1, mse = mse_(B1)))

Iteranion = 0, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 10, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 20, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 30, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 40, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 50, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 60, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 70, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 80, B1 = 0.04166800643086872, mse =0.022847216639871392
Iteranion = 90, B1 = 0.04166800643086872, mse =0.022847216639871392


In [104]:
for i in range (3000):
    B1 -= alpha * (2/n)  * np.sum ((B1 * x - y) * x)
    if i % 500 == 0:
        print ('Iteranion = {i}, B1 = {B1}, mse ={mse}'.format(i= i, B1 = B1, mse = mse_(B1)))

Iteranion = 0, B1 = 0.04166800663447113, mse =0.022847216639871513
Iteranion = 500, B1 = 0.04166800643986129, mse =0.022847216639871402
Iteranion = 1000, B1 = 0.0416680064312654, mse =0.022847216639871392
Iteranion = 1500, B1 = 0.04166800643088573, mse =0.022847216639871406
Iteranion = 2000, B1 = 0.041668006430868966, mse =0.022847216639871406
Iteranion = 2500, B1 = 0.04166800643086872, mse =0.022847216639871392


In [107]:
mse_(0.041668)

0.022847216640000008

In [109]:
import scipy.stats as stats

In [116]:
stats.norm.ppf(0.975)

1.959963984540054

In [118]:
stats.f.ppf(1-0.05, 1, 6)

5.987377607273699

In [147]:
SSf = sum((y_pred - np.mean(p))**2)
SSf

3.614987541528235

In [148]:
SSo = np.sum(( p - y_pred)**2)
SSo

0.16001245847176088

In [149]:
df1 = 1
df2 = 6

In [150]:
Msf = SSf/ df1
Msf


3.614987541528235

In [151]:
Mso = SSo / df2
Mso

0.02666874307862681

In [152]:
F =  Msf / Mso 
F

135.55147803067638

In [156]:
### это  mso : So2 = np.sum((p-y_pred)**2)/(n-2)
#So2

In [160]:
sb = np.sqrt( Mso / np.sum((s - np.mean(s))**2))

In [161]:
sb # стандартная ошибка коэффициента

0.0033279211856704766

In [163]:
0.03874584717607981/sb

11.642657687601963

In [164]:
b1/sb

11.642657687601963

Связь коэффициента

In [165]:
np.sqrt(F)

11.642657687601933

In [178]:
sa = np.sqrt( (Mso * np.sum( s **2) ) / ( n * sum ( (s - np.mean(s))**2)))
sa  #  стандартная ошибка параметра а

array([0.18558943])

In [179]:
ta = b0 / sa
ta

array([0.92392171])

In [180]:
# t табл для 6 степ свободы и альфа 5%  2.447

intercept   -не имеет статистической значимости

In [182]:
# b1 -статистически значимый