In [53]:
import numpy as np
x=np.array([35,45,190,200,40,70,54,150,120,110])
x


array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [54]:
n=x.shape
n

(10,)

In [55]:
y=np.array([401,574,874,919,459,739,653,902,746,832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [56]:
y.shape

(10,)

In [57]:
b=(np.mean(x*y)-np.mean(x)*np.mean(y))/(np.mean(x**2)-np.mean(x)**2)
b

2.620538882402765

In [58]:
a=np.mean(y)-b*np.mean(x)
a

444.1773573243596

In [62]:
x=x.reshape((10,1))
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [63]:
y=y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [66]:
b=np.dot(np.linalg.inv(np.dot(x.T,x)),x.T@y)
b

array([[5.88982042]])

In [67]:
x=np.hstack([np.ones((10,1)),x])
x

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [68]:
b=np.dot(np.linalg.inv(np.dot(x.T,x)),np.dot(x.T,y))
b

array([[444.17735732],
       [  2.62053888]])

In [70]:
import numpy as np
x=np.array([35,45,190,200,40,70,54,150,120,110])

In [71]:
y=np.array([401,574,874,919,459,739,653,902,746,832])

In [72]:
b1=0.1
n=10
alpha=1e-6

In [75]:
def mse_(b1,y=y,x=x,n=10):
    return np.sum((b1*x-y)**2)/n

In [77]:
for i in range(1000):
    b1 -=alpha*(2/n)*np.sum((b1*x-y)*x)
    if i%100==0:
        print('iteration:{i}, b1={b1}, mse={mse}'.format(i=i,b1=b1,mse=mse_(b1)))

iteration:0, b1=2.6698789606516935, mse=199352.96411174876
iteration:100, b1=5.692835432193034, mse=57051.433003054815
iteration:200, b1=5.877769553381888, mse=56518.85910026643
iteration:300, b1=5.889083189387522, mse=56516.86590342786
iteration:400, b1=5.88977531888123, mse=56516.8584437427
iteration:500, b1=5.889817660992628, mse=56516.85841582429
iteration:600, b1=5.889820251337954, mse=56516.8584157198
iteration:700, b1=5.889820409806407, mse=56516.8584157194
iteration:800, b1=5.889820419500961, mse=56516.8584157194
iteration:900, b1=5.8898204200940425, mse=56516.85841571941
